#!/bin/sh
SOURCE="$1"; shift 1

# Allow fault installation override.
if test x"$FAULT" = x""
then
	FAULT="$SOURCE"
fi

PUBLISH="$(pwd)/docs"

x ()
{
	echo "-> $@"
	"$@"
}

fault ()
{
	"$FAULT/bin/fault-tool" "$@"
}

FPROTOCOL='protocol+Interface Protocols+interface+http://if.fault.io/'

for y in "$FPROTOCOL"
do
	(IFS='+'
		set -- $y
		unset IFS

		ldir="$1"; shift 1
		title="$1"; shift 1
		fcontext="$1"; shift 1
		uid="$1"; shift 1

		if ! test -d "$SOURCE/$ldir"
		then
			echo >&2 "Directory '$SOURCE/$ldir' does not exist; skipping."
			exit
		fi

		if test x"$FACTORS" = x"update"
		then
			x fault fictl delineate -D"$SOURCE/$ldir"
		fi

		x \
		fault python \
		system.chapters.print web factors \
			--corpus-root="$uid" \
			--corpus-title="$title" -P"$fcontext". \
			"$PUBLISH" "$SOURCE/$ldir"
	)
done
